<?php

/**
 * This is the model base class for the table "{{lookup}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Lookup".
 *
 * Columns in table "{{lookup}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $code
 * @property string $type
 * @property integer $position
 *
 */
abstract class BaseLookup extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{lookup}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Lookup|Lookups', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, code, type, position', 'required'),
			array('code, position', 'numerical', 'integerOnly'=>true),
			array('name, type', 'length', 'max'=>128),
			array('id, name, code, type, position', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'code' => Yii::t('app', 'Code'),
			'type' => Yii::t('app', 'Type'),
			'position' => Yii::t('app', 'Position'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('code', $this->code);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('position', $this->position);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}